### ISSUE TITLE
Nymn, there's a security loophole in your code. Check this ASAP!

### ISSUE THREAD

**Issue by ms-dc** [Nymnion/Project-NYMN#1]
![Sem título](https://user-images.githubusercontent.com/15190187/232321013-f8267186-67e4-414d-87b6-2d402abd023a.png)

**Comment by mpsparrow** [comment]
![image](https://user-images.githubusercontent.com/6476699/232534689-24b0dce0-f39a-4c3d-b112-aa76576b2645.png)
